// Generated by CoffeeScript 1.6.3
(function() {
  Meteor.saveFile = function(blob, name, path, type, callback) {
    var encoding, fileReader, method;
    fileReader = new FileReader();
    encoding = 'binary';
    type = type || 'binary';
    switch (type) {
      case 'text':
        method = 'readAsText';
        encoding = 'utf8';
        break;
      case 'binary':
        method = 'readAsBinaryString';
        encoding = 'binary';
        break;
      default:
        method = 'readAsBinaryString';
        encoding = 'binary';
    }
    fileReader.onload = function(file) {
      return Meteor.call('saveFile', file.srcElement.result, name, path, encoding, callback);
    };
    return fileReader[method](blob);
  };

}).call(this);
