// Generated by CoffeeScript 1.6.3
(function() {
  Template.input.events({
    'click button': function(ev) {
      var date, post, time;
      ev.preventDefault();
      date = new Date;
      time = date.getTime();
      post = {
        from: {
          id: Meteor.userId(),
          name: Meteor.user().profile.name,
          avatar_url: Meteor.user().profile.avatar_url
        },
        text: text.value,
        createdAt: time
      };
      text.value = "";
      return Posts.insert(post);
    }
  });

}).call(this);
