// Generated by CoffeeScript 1.6.3
(function() {
  Template.input.events({
    'keydown #text': function(ev) {
      var date, post, time;
      if (ev.which === 13) {
        ev.preventDefault();
        date = new Date;
        time = date.getTime();
        post = {
          from: {
            id: Meteor.userId(),
            name: Meteor.user().profile.login,
            avatar_url: Meteor.user().profile.avatar_url
          },
          text: text.value,
          createdAt: time
        };
        text.value = "";
        return Posts.insert(post);
      }
    }
  });

}).call(this);
