// Generated by CoffeeScript 1.6.3
(function() {
  Template.user_loggedout.events({
    'click #login': function(ev, tmpl) {
      return Meteor.loginWithGithub({
        requestPermissions: ['user', 'user:email', 'public_repo', 'gist']
      });
    }
  });

}).call(this);
