// Generated by CoffeeScript 1.6.3
(function() {
  window.Gist = (function() {
    function Gist() {}

    Gist.prototype.pattern = function(input) {
      return input.match(/^!gist /);
    };

    Gist.prototype.run = function(input) {
      if (this.pattern(input)) {
        return console.log(input);
      }
    };

    return Gist;

  })();

}).call(this);
