// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.NotificationProcessor = (function() {
    function NotificationProcessor() {}

    NotificationProcessor.prototype.pattern = function() {
      return "@" + Meteor.user().profile.login;
    };

    NotificationProcessor.prototype.run = function(message) {
      var notification;
      if (Notification.permission === 'granted') {
        return notification = new Notification("XXX Says:", {
          body: "BLAH BLAH",
          icon: "http://i.stack.imgur.com/dmHl0.png"
        });
      }
    };

    return NotificationProcessor;

  })();

  $(function() {
    return $(window).on('click', function() {
      if (Notification.permission !== 'denied') {
        return Notification.requestPermission(function(permission) {
          if (__indexOf.call(Notification, 'permission') < 0) {
            return Notification.permission = permission;
          }
        });
      }
    });
  });

}).call(this);
