// Generated by CoffeeScript 1.6.3
(function() {
  var __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  window.NotificationProcessor = (function() {
    function NotificationProcessor() {}

    NotificationProcessor.prototype.pattern = function() {
      return new RegExp("@" + Meteor.user().profile.login, 'i');
    };

    NotificationProcessor.prototype.run = function(post) {
      var notification;
      if (Notification.permission === 'granted') {
        return notification = new Notification(post.from.name + "Says:", {
          body: post.text,
          icon: post.from.avatar_url
        });
      }
    };

    return NotificationProcessor;

  })();

  $(function() {
    return $(window).on('click', function() {
      if (Notification.permission !== 'denied') {
        return Notification.requestPermission(function(permission) {
          if (__indexOf.call(Notification, 'permission') < 0) {
            return Notification.permission = permission;
          }
        });
      }
    });
  });

}).call(this);
