// Generated by CoffeeScript 1.6.3
(function() {
  var notifications;

  window.PreRenderer = (function() {
    function PreRenderer(plugins) {
      this.plugins = plugins;
    }

    PreRenderer.prototype.render = function(message) {
      var plugin, _i, _len, _ref;
      _ref = this.plugins;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        plugin = _ref[_i];
        if (plugin.pattern.test(message.text)) {
          message.text = plugin.run(message.text);
        }
      }
      return message;
    };

    return PreRenderer;

  })();

  notifications = new NotificationProcessor;

  window.preRenderer = new PreRenderer([notifications]);

}).call(this);
